static char *simple_player_xpm[] = {
  "12 12 2",
  "  255",
  ". 9",
  "    ....    ",
  "   ......   ",
  "  ........  ",
  " .......... ",
  "............",
  "............",
  "............",
  "............",
  " .......... ",
  "  ........  ",
  "   ......   ",
  "    ....    "
};

static char *enemy_xpm[] = {
  "20 20 1",
  ". 36",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "...................."
};

static char *delete_enemy_xpm[] = {
  "20 20 1",
  ". 0",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "...................."
};




static char *player_xpm[] = {
  "80 80 5",
  " 	255",
  ".	20",
  "h	54",
  "g	0",
  "+	0",
"                                                                                ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                                                    ...+++...                   ",
"                            .....................   ...+++...                   ",
"                          ...................................                   ",
"                          ....................................                  ",
"                        ...gghhhhhhhhhggghhhhhhh..............                  ",
"                        ...gghhhhhhhhhggghhhhhhhhh...++++++...                  ",
"                       ....gghhhhhhhhhggghhhhhhhhh.....++++...                  ",
"                       ...ggghhhhhhhhhggghhhhhhhhhgg...++++...                  ",
"                     .....ggghhhhhhhhhggghhhhhhhhhgg....+++...                  ",
"                     ...hhggghhhhhhhhhggghhhhhhhhhggg...+++...                  ",
"                    ....hhggghhhhhhhhhggghhhhhhhhhggg....++...                  ",
"                    ...hhhggghhhhhhhhhggghhhhhhhhhgggh...++...                  ",
"                   ....hhhggghhhhhhhhhggghhhhhhhhhgggh....+...                  ",
"                   ...hhhhggghhhhhhhhhggghhhhhhhhhggghh...+...                  ",
"                 .....hhhhggghhhhhhhhhggghhhhhhhhhggghh.......                  ",
"                 ...hhhhhhggghhhhhhhhhggghhhhhhhhhggghhh......                  ",
"               .....hhhhhhggghhhhhhhhhggghhhhhhhhhggghhh......                  ",
"          ........ghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh.........             ",
"       ...........ghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh............          ",
"       ........hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg..........          ",
"     .....hh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hh.....        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     .....hh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hh.....        ",
"     ..........hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh........          ",
"     ..........hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh........          ",
"         ......hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh......            ",
"              ...gghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg...                 ",
"              ...gghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg...                 ",
"              .....hhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg...                 ",
"                ...hhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh...                   ",
"                .....hhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh...                   ",
"                  ...hhhhhggghhhhhhhhhggghhhhhhhhhggghhh.....                   ",
"                  .....hhhggghhhhhhhhhggghhhhhhhhhggghhh...                     ",
"                    ...........hhhhhhhggghhhhh.............                     ",
"                    ......................................                      ",
"                      ....................................                      ",
"                               ................                                 ",
"                                                                                "
};








/* XPM */
static char *direct_player_xpm[] = {
"80 80 68 1",
" 	c #FF8409",
".	c #5E250D",
"+	c #5B5B5B",
"@	c #AAA9AA",
"#	c #AAA9A9",
"$	c #A7A7A7",
"%	c #A5A5A5",
"&	c #A5A5A4",
"*	c #A2A2A2",
"=	c #A2A2A3",
"-	c #A0A1A0",
";	c #A0A0A0",
">	c #9E9D9E",
",	c #9D9D9D",
"'	c #9B9B9B",
")	c #999999",
"!	c #99999A",
"~	c #979697",
"{	c #979797",
"]	c #959495",
"^	c #949594",
"/	c #929292",
"(	c #8F908F",
"_	c #8F8F90",
":	c #8E8E8D",
"<	c #8E8D8E",
"[	c #8B8B8B",
"}	c #888889",
"|	c #888988",
"1	c #868686",
"2	c #868786",
"3	c #848484",
"4	c #828282",
"5	c #818282",
"6	c #808080",
"7	c #7F7F80",
"8	c #7D7D7D",
"9	c #7A7A7A",
"0	c #7B7B7A",
"a	c #787878",
"b	c #797978",
"c	c #767576",
"d	c #767676",
"e	c #737474",
"f	c #747473",
"g	c #000000",
"h	c #FFB600",
"i	c #6B6A6B",
"j	c #6B6B6B",
"k	c #6A6A6B",
"l	c #6A6A6A",
"m	c #6B6B6A",
"n	c #696969",
"o	c #676867",
"p	c #686868",
"q	c #676667",
"r	c #656565",
"s	c #666665",
"t	c #666566",
"u	c #636363",
"v	c #616161",
"w	c #616160",
"x	c #5E5F5F",
"y	c #5E5F5E",
"z	c #5C5C5C",
"A	c #5B240C",
"B	c #622B0D",
"C	c #66300D",
"                                                                                ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...+++++...                  ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                   ...........                  ",
"                                                    ...+@#...                   ",
"                                                    ...+$$...                   ",
"                                                    ...+%&...                   ",
"                                                    ...+*=...                   ",
"                                                    ...+-;...                   ",
"                                                    ...+>,...                   ",
"                                                    ...+''...                   ",
"                                                    ...+)!...                   ",
"                                                    ...+~{...                   ",
"                                                    ...+]^...                   ",
"                                                    ...+//...                   ",
"                                                    ...+(_...                   ",
"                                                    ...+:<...                   ",
"                                                    ...+[[...                   ",
"                                                    ...+}|...                   ",
"                                                    ...+12...                   ",
"                                                    ...+33...                   ",
"                                                    ...+45...                   ",
"                                                    ...+67...                   ",
"                                                    ...+88...                   ",
"                                                    ...+90...                   ",
"                                                    ...+ab...                   ",
"                                                    ...+cd...                   ",
"                            .....................   ...+ef...                   ",
"                          ...................................                   ",
"                          ....................................                  ",
"                        ...gghhhhhhhhhggghhhhhhh..............                  ",
"                        ...gghhhhhhhhhggghhhhhhhhh...ijkilm...                  ",
"                       ....gghhhhhhhhhggghhhhhhhhh.....nopp...                  ",
"                       ...ggghhhhhhhhhggghhhhhhhhhgg...qrst...                  ",
"                     .....ggghhhhhhhhhggghhhhhhhhhgg....uuu...                  ",
"                     ...hhggghhhhhhhhhggghhhhhhhhhggg...vvw...                  ",
"                    ....hhggghhhhhhhhhggghhhhhhhhhggg....xy...                  ",
"                    ...hhhggghhhhhhhhhggghhhhhhhhhgggh...zz...                  ",
"                   ....hhhggghhhhhhhhhggghhhhhhhhhgggh....+...                  ",
"                   ...hhhhggghhhhhhhhhggghhhhhhhhhggghh...+...                  ",
"                 .....hhhhggghhhhhhhhhggghhhhhhhhhggghh.......                  ",
"                 ...hhhhhhggghhhhhhhhhggghhhhhhhhhggghhh......                  ",
"               .....hhhhhhggghhhhhhhhhggghhhhhhhhhggghhh......                  ",
"          ........ghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh.........             ",
"       ...........ghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh............          ",
"       ........hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg..........          ",
"     .....hh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hh.....        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     ...hhhh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hhhh...        ",
"     .....hh...hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh...hh.....        ",
"     ..........hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh........          ",
"     ..........hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh........          ",
"         ......hggghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgggh......            ",
"              ...gghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg...                 ",
"              ...gghhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg...                 ",
"              ...A.hhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhhgg...                 ",
"                ...hhhhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh...                   ",
"                .....hhhhhggghhhhhhhhhggghhhhhhhhhggghhhhh...                   ",
"                  ...hhhhhggghhhhhhhhhggghhhhhhhhhggghhh.....                   ",
"                  .....hhhggghhhhhhhhhggghhhhhhhhhggghhh...                     ",
"                    ........BBChhhhhhhggghhhhh.............                     ",
"                    ......................................                      ",
"                      ....................................                      ",
"                               ................                                 ",
"                                                                                "};
